// Code generated by viewc. DO NOT EDIT.
//
// source:  settings.ingv
// format:  version 1
// nodes:   7
// digest:  8c676cb9
//
// The document is emitted as data, not as widget calls: view.view_play
// remains the single implementation of what a node means.
package views

import "ingot:view"

@(private)
settings_text :: "rootSettingsenabledEnabledvolumeVolumeactionssaveSavecancelCancel"

@(private)
settings_nodes := [7]view.View_Node {
	{
		kind = .Panel,
		parent = -1,
		first_child = 1,
		next_sibling = -1,
		key_offset = 0,
		key_length = 4,
		gap = .MD,
		padding = .LG,
	},
	{
		kind = .Section_Header,
		parent = 0,
		first_child = -1,
		next_sibling = 2,
		label_offset = 4,
		label_length = 8,
	},
	{
		kind = .Checkbox,
		parent = 0,
		first_child = -1,
		next_sibling = 3,
		key_offset = 12,
		key_length = 7,
		label_offset = 19,
		label_length = 7,
		binding = 0,
	},
	{
		kind = .Slider,
		parent = 0,
		first_child = -1,
		next_sibling = 4,
		key_offset = 26,
		key_length = 6,
		label_offset = 32,
		label_length = 6,
		binding = 1,
		number_hi = 1,
		number_step = 0.05,
	},
	{
		kind = .Flex_Row,
		parent = 0,
		first_child = 5,
		next_sibling = -1,
		key_offset = 38,
		key_length = 7,
		gap = .SM,
		size_main = 32,
	},
	{
		kind = .Button,
		parent = 4,
		first_child = -1,
		next_sibling = 6,
		key_offset = 45,
		key_length = 4,
		label_offset = 49,
		label_length = 4,
		track = {kind = .Grow, weight = 1},
	},
	{
		kind = .Button,
		parent = 4,
		first_child = -1,
		next_sibling = -1,
		key_offset = 53,
		key_length = 6,
		label_offset = 59,
		label_length = 6,
		style = .Ghost,
		track = {kind = .Fixed, basis = 80},
	},
}

// settings returns the generated document, ready for view.view_play.
settings :: proc() -> view.View {
	return view.View{nodes = settings_nodes[:], text = settings_text}
}
