// Generating Odin source from a document.
//
// Goal: ship a view with no runtime parse and no runtime format-version risk,
// without introducing a second implementation of what a node means.
//
// Method: emit the *document*, not the widget calls. The output is a static
// View literal and a string constant; the generated procedure hands it to
// view_play, which stays the only thing that knows what a kind does. An earlier
// design emitted unrolled widget calls, which would have meant two emitters and
// a differential test to detect them drifting - a copy that drifts is exactly
// what TIGER_STYLE.md warns against, and proposing CI to catch the drift is
// adopting the debt rather than avoiding it.
//
// Two properties of the output are load-bearing:
//
//   - The node array is emitted at its exact length, never at VIEW_NODES_MAX.
//     A [512]View_Node with a static initialiser would put ~69 KB of mostly
//     zeros in .data and fail scripts/check_wasm_bloat.py, which exists because
//     a global reaches .data the moment it has an initialiser.
//   - Text is one string constant, so it lands in .rodata rather than being
//     rebuilt at startup.
package view

import "core:fmt"
import "core:strings"

// GENERATE_LINE_COLUMNS is the repository's physical line limit. The generator
// polices itself against it rather than being excluded from the gate, because a
// generator that emits unformattable code makes every consumer's check fail.
GENERATE_LINE_COLUMNS :: 100

Generate_Options :: struct {
	package_name: string, // defaults to "views"
	symbol:       string, // base name for the emitted symbols
	source_path:  string, // recorded in the header comment for provenance
}

// view_generate writes Odin source for view into a builder owned by the caller.
// It returns ok = false only when the options are unusable; a document that got
// this far has already been validated.
view_generate :: proc(b: ^strings.Builder, view: View, options: Generate_Options) -> (ok: bool) {
	assert(b != nil, "view_generate: nil builder")
	assert(len(view.nodes) <= VIEW_NODES_MAX, "view_generate: too many nodes")
	symbol := options.symbol
	if !identifier_ok(symbol) do return false
	package_name := options.package_name if options.package_name != "" else "views"
	if !identifier_ok(package_name) do return false

	generate_header(b, view, options, package_name)
	generate_text(b, view, symbol)
	generate_nodes(b, view, symbol)
	generate_accessor(b, symbol)
	return true
}

// generate_header records where the source came from, which format version it
// was written against, and the document's checksum. The checksum is what lets a
// reviewer tell whether a regenerated file actually changed.
@(private = "file")
generate_header :: proc(
	b: ^strings.Builder,
	view: View,
	options: Generate_Options,
	package_name: string,
) {
	assert(b != nil, "generate_header: nil builder")
	fmt.sbprintln(b, "// Code generated by viewc. DO NOT EDIT.")
	fmt.sbprintln(b, "//")
	if options.source_path != "" {
		fmt.sbprintfln(b, "// source:  %s", options.source_path)
	}
	fmt.sbprintfln(b, "// format:  version %d", VIEW_FORMAT_VERSION)
	fmt.sbprintfln(b, "// nodes:   %d", len(view.nodes))
	fmt.sbprintfln(b, "// digest:  %08x", view_digest(view))
	fmt.sbprintln(b, "//")
	fmt.sbprintln(b, "// The document is emitted as data, not as widget calls: view.view_play")
	fmt.sbprintln(b, "// remains the single implementation of what a node means.")
	fmt.sbprintfln(b, "package %s", package_name)
	fmt.sbprintln(b, "")
	fmt.sbprintln(b, `import "ingot:view"`)
	fmt.sbprintln(b, "")
}

// generate_text emits the blob as one string constant. Escaping is explicit and
// conservative: any byte outside printable ASCII becomes \x??, so the output is
// valid source regardless of what the builder interned.
@(private = "file")
generate_text :: proc(b: ^strings.Builder, view: View, symbol: string) {
	assert(b != nil, "generate_text: nil builder")
	fmt.sbprintln(b, "@(private)")
	fmt.sbprintf(b, "%s_text :: \"", symbol)
	for byte in transmute([]u8)view.text {
		write_escaped_byte(b, byte)
	}
	strings.write_string(b, "\"\n\n")
}

@(private = "file")
write_escaped_byte :: proc(b: ^strings.Builder, value: u8) {
	assert(b != nil, "write_escaped_byte: nil builder")
	switch value {
	case '"':
		strings.write_string(b, "\\\"")
	case '\\':
		strings.write_string(b, "\\\\")
	case '\n':
		strings.write_string(b, "\\n")
	case '\t':
		strings.write_string(b, "\\t")
	case '\r':
		strings.write_string(b, "\\r")
	case:
		if value < 0x20 || value >= 0x7f {
			fmt.sbprintf(b, "\\x%02x", value)
			return
		}
		strings.write_byte(b, value)
	}
}

// generate_nodes emits the array at its exact length, one field per line, which
// is odinfmt's canonical form for a multi-line composite literal.
//
// Matching the formatter exactly is deliberate. check.sh runs odinfmt over
// every tracked .odin file, so a generated file that the formatter would
// rewrite fails the gate in whatever repository it lands in. Emitting the
// canonical form means the generator polices itself instead of needing an
// exclusion, and the staleness test can compare bytes rather than reformat.
@(private = "file")
generate_nodes :: proc(b: ^strings.Builder, view: View, symbol: string) {
	assert(b != nil, "generate_nodes: nil builder")
	fmt.sbprintfln(b, "@(private)")
	fmt.sbprintfln(b, "%s_nodes := [%d]view.View_Node {{", symbol, len(view.nodes))
	for node in view.nodes {
		generate_node(b, node)
	}
	fmt.sbprintln(b, "}")
	fmt.sbprintln(b, "")
}

@(private = "file")
generate_node :: proc(b: ^strings.Builder, node: View_Node) {
	assert(b != nil, "generate_node: nil builder")
	fmt.sbprintln(b, "\t{")
	fmt.sbprintfln(b, "\t\tkind = .%v,", node.kind)
	// Links are always written, including the -1 sentinels: a reader checking
	// tree structure in a diff should not have to remember the default.
	fmt.sbprintfln(b, "\t\tparent = %d,", node.parent)
	fmt.sbprintfln(b, "\t\tfirst_child = %d,", node.first_child)
	fmt.sbprintfln(b, "\t\tnext_sibling = %d,", node.next_sibling)
	generate_node_text(b, node)
	generate_node_style(b, node)
	generate_node_numbers(b, node)
	fmt.sbprintln(b, "\t},")
}

@(private = "file")
generate_node_text :: proc(b: ^strings.Builder, node: View_Node) {
	assert(b != nil, "generate_node_text: nil builder")
	if node.key_length != 0 {
		fmt.sbprintfln(b, "\t\tkey_offset = %d,", node.key_offset)
		fmt.sbprintfln(b, "\t\tkey_length = %d,", node.key_length)
	}
	if node.label_length != 0 {
		fmt.sbprintfln(b, "\t\tlabel_offset = %d,", node.label_offset)
		fmt.sbprintfln(b, "\t\tlabel_length = %d,", node.label_length)
	}
	if node.value_length != 0 {
		fmt.sbprintfln(b, "\t\tvalue_offset = %d,", node.value_offset)
		fmt.sbprintfln(b, "\t\tvalue_length = %d,", node.value_length)
	}
	if node.binding != VIEW_BINDING_NONE {
		fmt.sbprintfln(b, "\t\tbinding = %d,", node.binding)
	}
}

@(private = "file")
generate_node_style :: proc(b: ^strings.Builder, node: View_Node) {
	assert(b != nil, "generate_node_style: nil builder")
	if node.flags != {} do fmt.sbprintfln(b, "\t\tflags = %v,", node.flags)
	if node.ink != {} do fmt.sbprintfln(b, "\t\tink = .%v,", node.ink)
	if node.text_role != {} do fmt.sbprintfln(b, "\t\ttext_role = .%v,", node.text_role)
	if node.gap != {} do fmt.sbprintfln(b, "\t\tgap = .%v,", node.gap)
	if node.padding != {} do fmt.sbprintfln(b, "\t\tpadding = .%v,", node.padding)
	if node.align != {} do fmt.sbprintfln(b, "\t\talign = .%v,", node.align)
	if node.justify != {} do fmt.sbprintfln(b, "\t\tjustify = .%v,", node.justify)
	if node.style != {} do fmt.sbprintfln(b, "\t\tstyle = .%v,", node.style)
}

@(private = "file")
generate_node_numbers :: proc(b: ^strings.Builder, node: View_Node) {
	assert(b != nil, "generate_node_numbers: nil builder")
	// A Track stays on one line: odinfmt keeps a short nested literal inline,
	// and every field it can carry fits well inside the column limit.
	if node.track != {} {
		track := strings.builder_make(context.temp_allocator)
		fmt.sbprintf(&track, "kind = .%v", node.track.kind)
		if node.track.basis != 0 do fmt.sbprintf(&track, ", basis = %d", node.track.basis)
		if node.track.weight != 0 do fmt.sbprintf(&track, ", weight = %d", node.track.weight)
		if node.track.percent != 0 do fmt.sbprintf(&track, ", percent = %v", node.track.percent)
		if node.track.min_size != 0 do fmt.sbprintf(&track, ", min_size = %d", node.track.min_size)
		if node.track.max_size != 0 do fmt.sbprintf(&track, ", max_size = %d", node.track.max_size)
		fmt.sbprintfln(b, "\t\ttrack = {{%s},", strings.to_string(track))
	}
	if node.size_main != 0 do fmt.sbprintfln(b, "\t\tsize_main = %d,", node.size_main)
	if node.integer != 0 do fmt.sbprintfln(b, "\t\tinteger = %d,", node.integer)
	if node.number_lo != 0 do fmt.sbprintfln(b, "\t\tnumber_lo = %v,", node.number_lo)
	if node.number_hi != 0 do fmt.sbprintfln(b, "\t\tnumber_hi = %v,", node.number_hi)
	if node.number_step != 0 do fmt.sbprintfln(b, "\t\tnumber_step = %v,", node.number_step)
}

// generate_accessor emits the one public symbol a consumer touches. It returns
// a View rather than exposing the arrays, so the generated file's shape stays
// an implementation detail and can change without breaking a consumer.
@(private = "file")
generate_accessor :: proc(b: ^strings.Builder, symbol: string) {
	assert(b != nil, "generate_accessor: nil builder")
	fmt.sbprintfln(b, "// %s returns the generated document, ready for view.view_play.", symbol)
	fmt.sbprintfln(b, "%s :: proc() -> view.View {{", symbol)
	fmt.sbprintfln(b, "\treturn view.View{{nodes = %s_nodes[:], text = %s_text}}", symbol, symbol)
	fmt.sbprintln(b, "}")
}

// view_digest is a content hash over the encoded document, recorded in the
// generated header so a reviewer can tell a real change from a re-run. It is
// the same CRC the file format uses, over the same bytes, for the same reason:
// one implementation rather than two.
view_digest :: proc(view: View) -> u32 {
	assert(len(view.nodes) <= VIEW_NODES_MAX, "view_digest: too many nodes")
	buffer := make([]u8, view_encoded_size(view), context.temp_allocator)
	written, ok := view_encode(view, buffer)
	assert(ok && written == len(buffer), "view_digest: encoding a valid document failed")
	return view_checksum(buffer[VIEW_HEADER_BYTES:])
}

// identifier_ok rejects a symbol that would not compile. The generator's
// output is source, so an unchecked name here becomes a syntax error in the
// consumer's build rather than a clear failure in the tool.
@(private = "file")
identifier_ok :: proc(name: string) -> bool {
	if name == "" do return false
	for index in 0 ..< len(name) {
		value := name[index]
		letter := (value >= 'a' && value <= 'z') || (value >= 'A' && value <= 'Z')
		digit := value >= '0' && value <= '9'
		if letter || value == '_' do continue
		if digit && index > 0 do continue
		return false
	}
	return true
}
